image: ghcr.io/cirruslabs/flutter:latest

stages:
  - build

build_android_release:
  stage: build
  only:
    - tags 
  script:
    - flutter clean
    - flutter pub get
    - flutter build apk --release
    - flutter build appbundle --release
  artifacts:
    name: "Android-Release-$CI_COMMIT_TAG"
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    expire_in: 60 days